// Also we can rename it as config.js , to store hardcoded things like urls, data etc..,
export const IMG_URL = 'https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/';

export const RESTAURANT_URL = 'https://www.swiggy.com/dapi/restaurants/list/v5?lat=16.501976&lng=80.639227&is-seo-homepage-enabled=true&page_type=DESKTOP_WEB_LISTING';

export const restaurantList = [
  {
    info: {
      id: '67849',
      name: 'Sri Sairam Parlour - Diamond Park',
      cloudinaryImageId: '51e49c361768f2d16cfff0dd624fdac7',
      locality: 'Diamond Park',
      areaName: 'Dwarka Nagar',
      costForTwo: '₹150 for two',
      cuisines: ['South Indian', 'Chinese', 'Tandoor', 'Juices', 'Sweets', 'Beverages'],
      avgRating: 4.3,
      veg: true,
      feeDetails: {
        restaurantId: '67849',
        fees: [{ name: 'BASE_DISTANCE', fee: 5000 }, { name: 'BASE_TIME' }, { name: 'ANCILLARY_SURGE_FEE' }],
        totalFee: 5000,
      },
      parentId: '12846',
      avgRatingString: '4.3',
      totalRatingsString: '10K+',
      sla: {
        deliveryTime: 31,
        lastMileTravel: 6.4,
        serviceability: 'SERVICEABLE',
        slaString: '31 mins',
        lastMileTravelString: '6.4 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2023-11-29 22:30:00', opened: true },
      badges: { imageBadges: [{ imageId: 'v1695133679/badges/Pure_Veg111.png', description: 'pureveg' }] },
      isOpen: true,
      type: 'F',
      badgesV2: {
        entityBadges: {
          textBased: {},
          imageBased: { badgeObject: [{ attributes: { imageId: 'v1695133679/badges/Pure_Veg111.png', description: 'pureveg' } }] },
          textExtendedBadges: {},
        },
      },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: { mediaType: 'ADS_MEDIA_ENUM_IMAGE', lottie: {}, video: {} },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: { link: 'swiggy://menu?restaurant_id=67849', text: 'RESTAURANT_MENU', type: 'DEEPLINK' },
  },

  {
    info: {
      id: '700178',
      name: 'Real Deepak Punjabi Dhaba',
      cloudinaryImageId: '56905d69fc9e1940a430573dadd233c3',
      locality: 'Opp Nstl Gate',
      areaName: 'N A D',
      costForTwo: '₹200 for two',
      cuisines: ['Indian', 'Chinese', 'Biryani', 'Snacks', 'Seafood', 'Salads', 'Beverages'],
      avgRating: 4,
      feeDetails: {
        restaurantId: '700178',
        fees: [{ name: 'BASE_DISTANCE', fee: 2900 }, { name: 'BASE_TIME' }, { name: 'ANCILLARY_SURGE_FEE' }],
        totalFee: 2900,
      },
      parentId: '5191',
      avgRatingString: '4.0',
      totalRatingsString: '1K+',
      sla: {
        deliveryTime: 25,
        lastMileTravel: 3.6,
        serviceability: 'SERVICEABLE',
        slaString: '25 mins',
        lastMileTravelString: '3.6 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2023-11-29 22:45:00', opened: true },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {
        header: '10% OFF',
        shortDescriptionList: [{ meta: 'Use TRYNEW', discountType: 'Percentage', operationType: 'RESTAURANT' }],
        descriptionList: [{ meta: '10% off up to ₹40 | Use code TRYNEW', discountType: 'Percentage', operationType: 'RESTAURANT' }],
      },
      type: 'F',
      badgesV2: { entityBadges: { textBased: {}, imageBased: {}, textExtendedBadges: {} } },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: { mediaType: 'ADS_MEDIA_ENUM_IMAGE', lottie: {}, video: {} },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: { link: 'swiggy://menu?restaurant_id=700178', text: 'RESTAURANT_MENU', type: 'DEEPLINK' },
  },
  {
    info: {
      id: '350035',
      name: 'CakeZone',
      cloudinaryImageId: '2857960242f8d1d4d390dc22a38c530e',
      locality: 'Gopalapatnam',
      areaName: 'Sai Dharani Castle',
      costForTwo: '₹200 for two',
      cuisines: ['Bakery', 'Desserts', 'Sweets', 'Ice Cream'],
      avgRating: 4.1,
      feeDetails: {
        restaurantId: '350035',
        fees: [{ name: 'BASE_DISTANCE', fee: 3400 }, { name: 'BASE_TIME' }, { name: 'ANCILLARY_SURGE_FEE' }],
        totalFee: 3400,
      },
      parentId: '7003',
      avgRatingString: '4.1',
      totalRatingsString: '1K+',
      sla: {
        deliveryTime: 36,
        lastMileTravel: 4.6,
        serviceability: 'SERVICEABLE',
        slaString: '36 mins',
        lastMileTravelString: '4.6 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2023-11-29 23:59:00', opened: true },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {
        header: '60% OFF',
        shortDescriptionList: [{ meta: 'Use TRYNEW', discountType: 'Percentage', operationType: 'RESTAURANT' }],
        descriptionList: [{ meta: '60% off up to ₹120 | Use code TRYNEW', discountType: 'Percentage', operationType: 'RESTAURANT' }],
      },
      type: 'F',
      badgesV2: { entityBadges: { textBased: {}, imageBased: {}, textExtendedBadges: {} } },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: { mediaType: 'ADS_MEDIA_ENUM_IMAGE', lottie: {}, video: {} },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: { link: 'swiggy://menu?restaurant_id=350035', text: 'RESTAURANT_MENU', type: 'DEEPLINK' },
  },
  {
    info: {
      id: '66797',
      name: 'Helapuri Restaurant-Jagadamba',
      cloudinaryImageId: 'ev8xridkgzdndgxtgm1w',
      locality: 'Jagadamba Junction',
      areaName: 'Dwarka Nagar',
      costForTwo: '₹250 for two',
      cuisines: ['Tandoor', 'Biryani', 'Chinese'],
      avgRating: 3.8,
      feeDetails: {
        restaurantId: '66797',
        fees: [{ name: 'BASE_DISTANCE', fee: 5700 }, { name: 'BASE_TIME' }, { name: 'ANCILLARY_SURGE_FEE' }],
        totalFee: 5700,
      },
      parentId: '95302',
      avgRatingString: '3.8',
      totalRatingsString: '10K+',
      promoted: true,
      adTrackingId: 'cid=9235851~p=4~eid=0000018c-19bc-696d-20c8-a48d00d3042d~srvts=1701238827373~45995',
      sla: {
        deliveryTime: 30,
        lastMileTravel: 7.4,
        serviceability: 'SERVICEABLE',
        slaString: '30 mins',
        lastMileTravelString: '7.4 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2023-11-29 22:30:00', opened: true },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {
        header: '₹125 OFF',
        shortDescriptionList: [{ meta: 'Use FLATDEAL', discountType: 'Flat', operationType: 'RESTAURANT' }],
        descriptionList: [{ meta: 'FLAT125 off | Use FLATDEAL', discountType: 'Flat', operationType: 'RESTAURANT' }],
      },
      type: 'F',
      badgesV2: { entityBadges: { imageBased: {}, textExtendedBadges: {}, textBased: {} } },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: { mediaType: 'ADS_MEDIA_ENUM_IMAGE', lottie: {}, video: {} },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: { link: 'swiggy://menu?restaurant_id=66797', text: 'RESTAURANT_MENU', type: 'DEEPLINK' },
  },
  {
    info: {
      id: '237344',
      name: 'LunchBox - Meals and Thalis',
      cloudinaryImageId: 'vp5jfcq8orjnmogqdmld',
      locality: 'laxmi nagar',
      areaName: 'Simhachalam',
      costForTwo: '₹200 for two',
      cuisines: ['Biryani', 'North Indian', 'Punjabi', 'Healthy Food', 'Desserts', 'Beverages'],
      avgRating: 3.9,
      feeDetails: {
        restaurantId: '237344',
        fees: [{ name: 'BASE_DISTANCE', fee: 3800 }, { name: 'BASE_TIME' }, { name: 'ANCILLARY_SURGE_FEE' }],
        totalFee: 3800,
      },
      parentId: '4925',
      avgRatingString: '3.9',
      totalRatingsString: '1K+',
      sla: {
        deliveryTime: 31,
        lastMileTravel: 5,
        serviceability: 'SERVICEABLE',
        slaString: '31 mins',
        lastMileTravelString: '5.0 km',
        iconType: 'ICON_TYPE_EMPTY',
      },
      availability: { nextCloseTime: '2023-11-29 23:59:00', opened: true },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {
        header: '50% OFF',
        shortDescriptionList: [{ discountType: 'FinalPrice', operationType: 'RESTAURANT' }],
        descriptionList: [{ meta: 'Get every item under 149', discountType: 'FinalPrice', operationType: 'RESTAURANT' }],
      },
      type: 'F',
      badgesV2: { entityBadges: { imageBased: {}, textExtendedBadges: {}, textBased: {} } },
      differentiatedUi: {
        displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
        differentiatedUiMediaDetails: { mediaType: 'ADS_MEDIA_ENUM_IMAGE', lottie: {}, video: {} },
      },
      reviewsSummary: {},
      displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
      restaurantOfferPresentationInfo: {},
    },
    analytics: {},
    cta: { link: 'swiggy://menu?restaurant_id=237344', text: 'RESTAURANT_MENU', type: 'DEEPLINK' },
  },
];
